### ISSUE TITLE
Use different paths for tasks

### ISSUE THREAD

**Issue by Phoscur** [csantanapr/grunt-cordovacli#26]
From my codebase I'm able to build two different apps (internal&external) for the same domain. 
But using the same gruntfile does do not work:
```
Cordova does not know undefined; try `cordova help` for a list of all the available commands.
```
```
 cordovacli:
      internal:
        options:
          path: './app/'
        plugins:
          options:
            command: 'plugin'
            action: 'add'
            plugins: cordovaPlugins
      external:
        options:
          path: './app-external/'
        plugins:
          options:
            command: 'plugin'
            action: 'add'
            plugins: cordovaPlugins
```
